# Generated by Django 3.1.3 on 2020-11-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201111_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='msg',
            new_name='message',
        ),
    ]
