# Generated by Django 3.1.3 on 2020-11-11 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201111_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='post_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
