# Generated by Django 3.1.3 on 2020-11-17 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201116_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
