# Generated by Django 3.1.3 on 2020-11-17 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedby',
        ),
        migrations.AddField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='liking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
