# Generated by Django 3.1.3 on 2020-11-20 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201117_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(blank=True, default=None, related_name='liking_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
